### ISSUE TITLE
Double data push in different Fence's

### ISSUE THREAD

**Issue by artpol84** [open-mpi/pmix#37]
We've already discussed this topic before but I'd like to rise this question again.
One of my last [commits](https://github.com/open-mpi/pmix/commit/f21d47962f126709d756feab4f2203b1c612ed60)  forces data to be kept on the server side at Fence completion. As the side effect I found that the following test configuration is failing:
```./pmix_test -n 4 --fence "[d|0:0-1;1:][0: ]" --ns-dist "3:1"```
I also found that previous versions are also failing on this test.
This test does the following:
1. creates 2 namespaces with names "smoky_nspace-0" and "smoky_nspace-1" correspondingly. 
2. Put's/Commits a set of predefined keys.
3. Performs first Fence with data exchage between ranks 0,1 from "smoky_nspace-0" and all ranks from the "smoky_nspace-1".
4. Verifies first key-value set.
5. Put's/Commits second set of predefined keys.
6. Performs second Fence between ranks of "smoky_nspace-0".
7. Verifies second key-value set.

The problem arises at second set verification (step 7). Since after first fence we touch all keys at step 5, we have the modex data received for all ranks of the first Fence. As the result after second Fence (without data exchange) some clients have local entries for the first set of keys in their modex tables. Because of that those clients won't try to retrieve new chunk of data from the server and will fail (saying that keys from the set #2 are not found).

Before my commit (related to stopping fence on server side) the following change was able to fix the problem:
```./pmix_test -n 4 --fence "[d|0:0-1;1:][**d |** 0: ]" --ns-dist "3:1"```
Second fence has data collection flag on which forces new set of keys to be collected and merged with the first set of keys.

As the solution I'd like to suggest the following:
1. On the server side we maintain multiple keys "modex-0", "modex-1" (for each fence touching particular rank) keeping track of all Fence's that was performed. We keep counter of all available modex keys on the server and **push it to the client as Fence response**. 
2. At the client side we keeps the counter of localy retrieved modex'es and has the total counter (from Fence response). If client searches local hash and is unable to found requested key it compares total number of modexes for this rank with it's local value. If local value is less - client needs to perform Get opetration from server and update it's local counter to be equal to latest one.

**Comment by rhc54** [comment]
A few comments, then a suggestion.

1. let’s be clear that there is no programming model today that would support this proposed use-case. Current models (e.g., MPI) only support one initial exchange of information. So what we are discussing is a hypothetical case that may occur sometime in the future.

2. there is no requirement that there be a fence operation after committing information. The introduction of a fence into your scenario is a distraction. Per a prior request, we moved the pushing of data to the local server into a separate commit API. So anything we do about multiple commits has to take into account that there may not be any further operation beyond the commit. This is why we have the “direct modex” function in the system - i.e., for those cases where someone requests info either after a non-collecting fence, or in the absence of any fence at all.

3. if the second commit is due to some fault recovery procedure, the procs will have been notified of the failure via the notification mechanism. At that time, we could invalidate their data store and they could “re-get” the data. Note that we shouldn’t do this under the covers - they should do it in response to a notification. So we may need to add a “delete info” API for this purpose.

4. creating these indices generates a race condition - there is no guarantee that fence operations will occur in the same series across multiple procs in different locations. I could have a fence that involves A,B,C and another that involved B,D,F - no way for A or C to know what index is correct for B, nor can we know what to do about the info that was already exchanged in whichever fence completed first. It was this race condition that led us to drop the indexing the last time this was discussed. I believe we may be able to find a way to solve this (no guarantee), but we really can’t rely on a non-global index to do it.

Finally, I suggest we table this use-case until PMIx 2.0. As I said, there is no current call for this behavior, and we should probably focus on getting support for 1.0 completed and distributed. We can deal with these future use-cases once we get that done.

HTH
Ralph

**Comment by artpol84** [comment]
Please, see below.

2015-08-02 7:13 GMT+03:00 rhc54 <notifications@github.com>:

> A few comments, then a suggestion.
>
> 1. let’s be clear that there is no programming model today that would
> support this proposed use-case. Current models (e.g., MPI) only support one
> initial exchange of information. So what we are discussing is a
> hypothetical case that may occur sometime in the future.


> 2. there is no requirement that there be a fence operation after
> committing information. The introduction of a fence into your scenario is a
> distraction. Per a prior request, we moved the pushing of data to the local
> server into a separate commit API. So anything we do about multiple commits
> has to take into account that there may not be any further operation beyond
> the commit. This is why we have the “direct modex” function in the system -
> i.e., for those cases where someone requests info either after a
> non-collecting fence, or in the absence of any fence at all.
>
> 3. if the second commit is due to some fault recovery procedure, the procs
> will have been notified of the failure via the notification mechanism. At
> that time, we could invalidate their data store and they could “re-get” the
> data. Note that we shouldn’t do this under the covers - they should do it
> in response to a notification. So we may need to add a “delete info” API
> for this purpose.
>
> 4. creating these indices generates a race condition - there is no
> guarantee that fence operations will occur in the same series across
> multiple procs in different locations. I could have a fence that involves
> A,B,C and another that involved B,D,F - no way for A or C to know what
> index is correct for B, nor can we know what to do about the info that was
> already exchanged in whichever fence completed first. It was this race
> condition that led us to drop the indexing the last time this was
> discussed. I believe we may be able to find a way to solve this (no
> guarantee), but we really can’t rely on a non-global index to do it.
>

I think that local indices will work fine in case when Fences are used. We
will fail to use them in case we will use direct modex.
Consider your example with Fences. Each process will append its actual
index at the time of Fence in it's Fence message so other will know how
many keys to request, locally they will need to keep track of the number of
keys that was already received.
This won't work with direct modex though.


>
> Finally, I suggest we table this use-case until PMIx 2.0. As I said, there
> is no current call for this behavior, and we should probably focus on
> getting support for 1.0 completed and distributed. We can deal with these
> future use-cases once we get that done.
>

I'm fine with this. However I believe that we need to implement some kind
of error checking that will help PMIx users to easily detect that they
doing something wrong. IMO it's not enough just to mention that in the
documentation. For example we can return VERR_NOT_SUPPORTED in case user
tries to Commit several times.
The thing that annoys me is that API itself provides you with ability to
use Commit several times while this will be erroneous behavior.


>
> HTH
> Ralph
>
> > On Aug 1, 2015, at 2:57 AM, Artem Polyakov <notifications@github.com>
> wrote:
> >
> > We've already discussed this topic before but I'd like to rise this
> question again.
> > One of my last commits <
> https://github.com/open-mpi/pmix/commit/f21d47962f126709d756feab4f2203b1c612ed60>
> forces data to be kept on the server side at Fence completion. As the side
> effect I found that the following test configuration is failing:
> > ./pmix_test -n 4 --fence "[d|0:0-1;1:][0: ]" --ns-dist "3:1"
> > I also found that previous versions are also failing on this test.
> > This test does the following:
> > 1. creates 2 namespaces with names "smoky_nspace-0" and "smoky_nspace-1"
> correspondingly.
> > 2. Put's/Commits a set of predefined keys.
> > 3. Performs first Fence with data exchage between ranks 0,1 from
> "smoky_nspace-0" and all ranks from the "smoky_nspace-1".
> > 4. Verifies first key-value set.
> > 5. Put's/Commits second set of predefined keys.
> > 6. Performs second Fence between ranks of "smoky_nspace-0".
> > 7. Verifies second key-value set.
> >
> > The problem arises at second set verification (step 7). Since after
> first fence we touch all keys at step 5, we have the modex data received
> for all ranks of the first Fence. As the result after second Fence (without
> data exchange) some clients have local entries for the first set of keys in
> their modex tables. Because of that those clients won't try to retrieve new
> chunk of data from the server and will fail (saying that keys from the set
> #2 <https://github.com/open-mpi/pmix/issues/2> are not found).
> >
> > Before my commit (related to stopping fence on server side) the
> following change was able to fix the problem:
> > ./pmix_test -n 4 --fence "[d|0:0-1;1:][**d |** 0: ]" --ns-dist "3:1"
> > Second fence has data collection flag on which forces new set of keys to
> be collected and merged with the first set of keys.
> >
> > As the solution I'd like to suggest the following:
> > 1. On the server side we maintain multiple keys "modex-0", "modex-1"
> (for each fence touching particular rank) keeping track of all Fence's that
> was performed. We keep counter of all available modex keys on the server
> and push it to the client as Fence response.
> > 2. At the client side we keeps the counter of localy retrieved modex'es
> and has the total counter (from Fence response). If client searches local
> hash and is unable to found requested key it compares total number of
> modexes for this rank with it's local value. If local value is less -
> client needs to perform Get opetration from server and update it's local
> counter to be equal to latest one.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/open-mpi/pmix/issues/37>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-mpi/pmix/issues/37#issuecomment-126986712>.
>



-- 
С Уважением, Поляков Артем Юрьевич
Best regards, Artem Y. Polyakov
